meteau/tridishop-service  8085


meteau/tridishop-profil   8084 


meteau/tridishop-products 8083 


meteau/tridishop-auth     8081


meteau/tridishop-api-gateway 3000


meteau/tridishop-admin    8082 


